{
 "title": "io",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "send/recv bytes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "target": "stats.io.recv_bytes" },
    { "target": "stats.io.send_bytes" }
   ]
  },
  {
   "title": "number of operations",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "target": "stats.io.op.all.completed" },
    { "target": "stats.io.op.recv.submitted" },
    { "target": "stats.io.op.send.submitted" }
   ]
  },
  {
   "title": "receive buffers usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "target": "stats.io.recv_buf_grp.*" }
   ]
  },
  {
   "title": "io_uring lops and processed cqe's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "target": "stats.io.cqes" },
    { "target": "stats.io.loops" }
   ]
  }
 ]
}