{
 "title": "topic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "depth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "stats.gauges.topic.sub_bench.msgs"
    },
    {
     "target": "stats.gauges.topic.sub_bench.bytes"
    },
    {
     "target": "stats.gauges.topic.sub_bench.capacity"
    }
   ]
  },
  {
   "title": "messages count/bytes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "stats.topic.sub_bench.message_count"
    },
    {
     "target": "stats.topic.sub_bench.message_bytes"
    }
   ]
  },
  {
   "title": "channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "stats.topic.sub_bench.channel.ch.*"
    }
   ]
  },
  {
   "title": "channel depth/in_fligth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "stats.gauges.topic.sub_bench.channel.ch.depth"
    },
    {
     "target": "stats.gauges.topic.sub_bench.channel.ch.in_flight_count"
    }
   ]
  }
 ]
}