{
 "title": "memory",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "broker total bytes / allocated bytes (capacity)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "target": "stats.gauges.broker.bytes" },
    { "target": "stats.gauges.broker.capacity" }
   ]
  },
  {
   "title": "system memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(stats.gauges.mem.size, 'vm')"
    },
    {
     "target": "alias(stats.gauges.mem.rss, 'rss')"
    }
   ]
  },
  {
   "title": "glibc memory",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(stats.gauges.mem.malloc.hblkhd, 'mmap allocated')"
    },
    {
     "target": "alias(stats.gauges.mem.malloc.arena, 'heap allocated')"
    },
    {
     "target": "alias(stats.gauges.mem.malloc.uordblks, 'in-use allocations')"
    },
    {
     "target": "alias(stats.gauges.mem.malloc.fordblks, 'free space')"
    },
    {
     "target": "alias(stats.gauges.mem.malloc.fsmblks, 'fastbin free')"
    },
    {
     "target": "alias(stats.gauges.mem.malloc.keepcost, 'releasable')"
    }
   ]
  }
 ]
}